name: Build and Publish image to Docker Hub
on: 
  [workflow_dispatch]

jobs:
  Publish_images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build backend and frontend images
        run: |
          docker build ./api/ -t sandunchathuranga/devops-qr-code-api:latest
          docker build ./front-end-nextjs/ -t sandunchathuranga/devops-qr-code-frontend:latest

      - name: Login to Docker Hub
        run: docker login -u sandunchathuranga -p ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Push images to Docker Hub
        run: |
          docker push sandunchathuranga/devops-qr-code-api:latest
          docker push sandunchathuranga/devops-qr-code-frontend:latest
